INSERT INTO themes (question_theme) VALUES ('História'), ('Matemática'), ('Geografia'), ('HTML'), ('CSS'), ('JavaScript'), ('Python'), ('Lógica');

INSERT INTO question (title, theme, right_option, option_A, option_B, option_C, option_D) VALUES 
('Em que ano ocorreu a Independência do Brasil?', 'História', 'option_B', '1808', '1822', '1889', '1500'),
('Quem foi o primeiro presidente do Brasil?', 'História', 'option_C', 'Dom Pedro II', 'Juscelino Kubitschek', 'Deodoro da Fonseca', 'Getúlio Vargas'),
('Qual foi o marco inicial da Revolução Francesa?', 'História', 'option_A', 'Queda da Bastilha', 'Declaração dos Direitos do Homem', 'Golpe do 18 de Brumário', 'Execução de Luís XVI'),
('Qual país foi responsável por colonizar o Brasil?', 'História', 'option_D', 'Espanha', 'Inglaterra', 'França', 'Portugal'),
('Quem foi o líder da Revolução Russa de 1917?', 'História', 'option_A', 'Vladimir Lenin', 'Josef Stalin', 'Leon Trótski', 'Mikhail Gorbachev'),
('Quanto é 7 + 5?', 'Matemática', 'option_C', '10', '11', '12', '13'),
('Qual é o resultado de 9 × 6?', 'Matemática', 'option_B', '42', '54', '48', '36'),
('Qual é a raiz quadrada de 81?', 'Matemática', 'option_A', '9', '8', '7', '6'),
('Se um triângulo tem lados de 3 cm, 4 cm e 5 cm, ele é um triângulo...', 'Matemática', 'option_D', 'Equilátero', 'Isósceles', 'Obtusângulo', 'Retângulo'),
('Quanto é 15 dividido por 3?', 'Matemática', 'option_B', '4', '5', '6', '7'),
('Qual é o maior oceano do mundo?', 'Geografia', 'option_A', 'Oceano Pacífico', 'Oceano Atlântico', 'Oceano Índico', 'Oceano Ártico'),
('Qual é o país com a maior população do mundo?', 'Geografia', 'option_B', 'Estados Unidos', 'China', 'Índia', 'Brasil'),
('Qual é o maior deserto do mundo?', 'Geografia', 'option_D', 'Deserto de Gobi', 'Deserto do Kalahari', 'Deserto da Arábia', 'Antártida'),
('Qual é o rio mais longo do mundo?', 'Geografia', 'option_C', 'Rio Amazonas', 'Rio Mississippi', 'Rio Nilo', 'Rio Yangtzé'),
('Quantos continentes existem no planeta?', 'Geografia', 'option_B', '5', '7', '6', '8'),
('Qual tag é usada para criar um link em HTML?', 'HTML', 'option_A', '<a>', '<link>', '<href>', '<url>'),
('Qual tag define um parágrafo em HTML?', 'HTML', 'option_B', '<h1>', '<p>', '<div>', '<span>'),
('Para que serve a tag <head> em um documento HTML?', 'HTML', 'option_C', 'Exibir o conteúdo', 'Criar rodapé', 'Conter metadados', 'Inserir imagem'),
('Qual propriedade CSS altera a cor do texto?', 'CSS', 'option_B', 'background-color', 'color', 'text-color', 'font-color'),
('Como aplicar uma cor de fundo em CSS?', 'CSS', 'option_A', 'background-color: red;', 'color: red;', 'text-color: red;', 'bg-color: red;'),
('Qual seletor aplica estilos a todos os parágrafos?', 'CSS', 'option_D', '#p', '.p', 'body p', 'p'),
('Qual comando exibe uma mensagem no console?', 'JavaScript', 'option_B', 'alert()', 'console.log()', 'prompt()', 'print()'),
('Como se declara uma variável em JavaScript ES6?', 'JavaScript', 'option_C', 'var nome', 'define nome', 'let nome', 'set nome'),
('Qual operador é usado para comparação estrita (valor e tipo)?', 'JavaScript', 'option_D', '=', '==', '<=>', '==='),
('Como se imprime algo na tela em Python?', 'Python', 'option_A', 'print()', 'console.log()', 'echo()', 'write()'),
('Qual palavra-chave define uma função em Python?', 'Python', 'option_B', 'function', 'def', 'func', 'lambda'),
('Como se comenta uma linha em Python?', 'Python', 'option_D', '//', '<!-- -->', '/* */', '#'),
('O que significa o operador lógico && em programação?', 'Lógica', 'option_C', 'OU lógico', 'Negação lógica', 'E lógico', 'Comparação'),
('Qual estrutura repete um bloco de código enquanto uma condição é verdadeira?', 'Lógica', 'option_B', 'if', 'while', 'switch', 'for each'),
('Qual estrutura condicional escolhe entre dois blocos de código?', 'Lógica', 'option_A', 'if-else', 'while', 'switch', 'loop');