version: "3"

services: 
  quiz_app:
    build: ./app
    command: npm start
    ports:
      - "3000:3000"
    volumes:
      - ./app:/home/quiz/app
      - nodemodules_app:/home/quiz/app/node_modules

  quiz_api:
    build: ./server
    command: npm run server
    ports:
      - "3001:3001"
    volumes:
      - ./server:/home/quiz/api
      - nodemodules_api:/home/quiz/api/node_modules

    depends_on:
      - database

  
  database:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: joao
      POSTGRES_PASSWORD: example
      POSTGRES_DB: quizapp
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./index.sql:/docker-entrypoint-initdb.d/index.sql
    ports:
      - "5432:5432"
      

volumes:
  postgres_data:
  nodemodules_api: {}
  nodemodules_app: {}
